remote_theme: just-the-docs/just-the-docs
color_scheme: dark
callouts:
  important:
    title: Important
    color: yellow
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  importantru:
    title: Важно
    color: yellow
  noteru:
    title: Примечание
    color: blue
  warningru:
    title: Внимание
    color: red