remote_theme: just-the-docs/just-the-docs
color_scheme: dark
callouts:
  important:
    title: !
    color: yellow
  note:
    title: #
    color: blue
  warning:
    title: !
    color: red
  importantru:
    title: !
    color: yellow
  noteru:
    title: Заметка
    color: blue
  warningru:
    title: !
    color: red