remote_theme: just-the-docs/just-the-docs
color_scheme: dark
callouts:
  important:
    title: Important
    color: yellow
  note:
    title: Note
    color: gray
  warning:
    title: Warning
    color: red